<?php

include_once('atrium_csflashcards.features.inc');

/**
 * Implementation of hook_help().
 */
function atrium_csflashcards_help($path) {
  // Central help page content.
  if ($path == 'help#atrium_csflashcards') {
    $help = '<h3>'. t('Flashcards') .'</h3>';
    $help .= '<p>'. t("Flashcards help your group share and study key concepts and terminology.") .'</p>';
    $help .= '<p>'. t("To create a new flashcard navigate Flashcards page for your group and click the \"Add Flashcards entry\" button. Enter titles for side 1 and side 2 of your card. Optionally add descriptions for each side and image to illustrate your concept. Then click \"Save\".") .'</p>';
    return $help;
  }

  // Contextual help content.
  if (context_isset('context', 'csflashcards_listing')) {
    if ($path == 'node/add/csflashcards') {
      $help = '';
      $help .= '<h3>'. t('Flashcards') .'</h3>';
      $help .= '<p>'. t("Post an entry to the Flashcards page for this group. The post will be shared with all team members on the Flashcards page, and they will be able to edit it. You can optionally notify other group members by checking their name in the notifications field.") .'</p>';
      return $help;
    }
    else {
      $help = '<h3>'. t('Flashcards') .'</h3>';
      $help .= '<p>'. t("Flashcards help your group share and study key concepts and terminology.") .'</p>';
      return $help;
    }
  }
}


/**
* Implementation of hook_init().
*/
function atrium_csflashcards_init() {
  drupal_add_css(drupal_get_path('module', 'atrium_csflashcards') .'/atrium_csflashcards.css');
}
